name: capstone
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^17.0.0
  permission_handler: ^11.1.0
  device_info_plus: ^9.1.2
  google_mlkit_text_recognition: ^0.15.0
  image_picker: ^1.0.4
  package_info_plus: ^5.0.1
  shared_preferences: ^2.2.2
  flutter_slidable: ^3.1.0
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon2.png"
  adaptive_icon_background: "#FFA500"
  adaptive_icon_foreground: "assets/icon/app_icon2.png"
  min_sdk_android: 21


flutter:
  uses-material-design: true

  assets:
    - assets/icon/app_icon2.png
